deployment:
  tasks:
    - export DEPLOYPATH=/home/zyakpszw/my-app
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/bin/npm install --legacy-peer-deps
    - /usr/bin/npm run build
