import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "SV Polymer Co., Ltd.",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

// app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );

}


// Since we have a `not-found.tsx` page on the root, a layout file
// is required, even if it's just passing children through.
