// app/[locale]/layout.tsx

import type { ReactNode } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "../[locale]/globals.css";

export const metadata = {
  title: "SV Polymer Co., Ltd.",
  description: "Generated by create next app",
};

export type Locale = "th" | "en";

type Props = {
  children: ReactNode;
  params: { locale: Locale };
};

export default function RootLayout({ children, params }: Props) {
  return (
    <html lang={params.locale}>
      <body>
        <Navbar locale={params.locale} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
