// /app/[locale]/layout.tsx
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";
// import { Locale } from "@/types";

export const metadata: Metadata = {
  title: "SV Polymer Co., Ltd.",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: { locale: string };
};

export default async function RootLayout({ children, params }: Props) {
  const awaitedParams = await Promise.resolve(params); // await params เพื่อบังคับแก้ error
  const { locale } = awaitedParams;

  return (
    <html lang={locale}>
      <body>
        <Navbar locale={locale} />
        <main>{children}</main>
        <Footer locale={locale} />
      </body>
    </html>
  );
}
